# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "ntsync" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2f7d156a-c7c0-4b80-825b-c8f8c6e62edc";
      fsType = "btrfs";
      options = [ "compress=zstd" ];
    };

  services.beesd.filesystems."root" = {
    spec = "/";
    hashTableSizeMB = 4096;
    extraOptions = [ "--loadavg-target" "4" ];
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C7B2-40E3";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/smallssd" =
    { device = "/dev/disk/by-uuid/18902baa-e45b-4e96-a292-6148c24c1b25";
      fsType = "btrfs";
      options = [ "compress=zstd" "nofail" ];
    };
      
  swapDevices =
    [ { device = "/dev/disk/by-uuid/14b368b3-141d-4351-b8de-c533400cff62"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp34s0.useDHCP = lib.mkDefault true;

  systemd.network.networks.enp34s0.dns = [
    "1.1.1.1"
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.amdgpu.overdrive.enable = true;
  hardware.amdgpu.initrd.enable = true;
  hardware.amdgpu.opencl.enable = true;


  services.hardware.openrgb = {
    enable = true;
  };
  services.xserver.videoDrivers = [ "amdgpu" ];
}
