{ spicetify-nix, ... }: {
  imports = [
    ./modules/key-repeat.nix
    ./modules/locale.nix
    ./modules/gnome.nix
    ./modules/x11-keymap.nix
    ./modules/cups.nix
    ./modules/pipewire.nix
    ./modules/steam.nix
    ./modules/gamemode.nix
    ./modules/env_vars.nix
    ./modules/fix-java-fonts.nix
    ./modules/distrobox.nix
    ./modules/syncthing.nix
    ./modules/mullvad.nix
    ./modules/stylix.nix
    ./modules/spicetify.nix
    ./modules/nix-ld.nix
    ./modules/systemd-boot.nix
    ./modules/bluetooth.nix
    ./modules/graphics.nix
    ./modules/network.nix
    ./modules/unfree-allow.nix
    ./modules/main-user.nix
    ./modules/dev-man-pages.nix
    ./modules/auto-gc.nix
    ./modules/flake-support.nix
    ./modules/flatpak.nix
    ./modules/ntfs-support.nix
    ./modules/bottles.nix
    ./modules/calibre.nix
    ./modules/audacity.nix
    ../packages/system_pkgs.nix
  ];
}
